const { Client } = require('@mathieuc/tradingview');
const nodemailer = require('nodemailer');
const emailConfig = require('./email-config');

const client = new Client();

// Tạo transporter cho email
const transporter = nodemailer.createTransport({
    service: emailConfig.service,
    auth: emailConfig.auth
});

// Biến lưu trữ dữ liệu báo cáo
let reportData = {
    startTime: new Date(),
    updates: [],
    currentPrice: null,
    highPrice: null,
    lowPrice: null,
    symbol: null,
    previousPrice: null,
    lastEmailSent: null // Thêm biến để theo dõi lần gửi email cuối
};

// Hàm tạo nội dung email
function generateEmailReport() {
    const now = new Date();
    const duration = Math.floor((now - reportData.startTime) / 1000 / 60); // phút
    
    let html = `
    <h2>☕ Coffee Robusta Price Report</h2>
    <p><strong>Symbol:</strong> ${reportData.symbol || 'N/A'}</p>
    <p><strong>Report Time:</strong> ${now.toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}</p>
    <p><strong>Monitoring Duration:</strong> ${duration} minutes</p>
    
    <h3>📊 Current Market Data</h3>
    <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
        <tr><td><strong>Current Price</strong></td><td>$${reportData.currentPrice?.toFixed(2) || 'N/A'}</td></tr>
        <tr><td><strong>High</strong></td><td>$${reportData.highPrice?.toFixed(2) || 'N/A'}</td></tr>
        <tr><td><strong>Low</strong></td><td>$${reportData.lowPrice?.toFixed(2) || 'N/A'}</td></tr>
    </table>
    
    <h3>📈 Recent Updates</h3>
    <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
        <tr>
            <th>Time</th>
            <th>Price</th>
            <th>Change</th>
            <th>Change %</th>
        </tr>
    `;
    
    // Lấy 10 update gần nhất
    const recentUpdates = reportData.updates.slice(-10);
    recentUpdates.forEach(update => {
        const changeColor = update.change >= 0 ? 'green' : 'red';
        html += `
        <tr>
            <td>${update.timestamp}</td>
            <td>$${update.price.toFixed(2)}</td>
            <td style="color: ${changeColor}">$${update.change.toFixed(2)}</td>
            <td style="color: ${changeColor}">${update.changePercent}%</td>
        </tr>
        `;
    });
    
    html += `
    </table>
    <p><em>Generated by Coffee Trading Bot - ${new Date().toISOString()}</em></p>
    `;
    
    return html;
}

// Hàm gửi email báo cáo
async function sendEmailReport() {
    try {
        const mailOptions = {
            from: emailConfig.from,
            to: emailConfig.to,
            subject: `☕ Coffee Robusta Price Report - ${new Date().toLocaleDateString('vi-VN')}`,
            html: generateEmailReport()
        };
        
        const info = await transporter.sendMail(mailOptions);
        console.log('📧 Email report sent successfully:', info.messageId);
    } catch (error) {
        console.error('❌ Failed to send email:', error.message);
    }
}

// Hàm gửi cảnh báo giá
async function sendPriceAlert(price, type) {
    try {
        const subject = type === 'high' ? 
            `🚨 HIGH PRICE ALERT - Coffee Robusta: $${price.toFixed(2)}` :
            `⚠️ LOW PRICE ALERT - Coffee Robusta: $${price.toFixed(2)}`;
            
        const html = `
        <h2>${type === 'high' ? '🚨' : '⚠️'} Price Alert</h2>
        <p><strong>Symbol:</strong> ${reportData.symbol}</p>
        <p><strong>Current Price:</strong> $${price.toFixed(2)}</p>
        <p><strong>Alert Type:</strong> ${type.toUpperCase()} PRICE</p>
        <p><strong>Threshold:</strong> $${emailConfig.priceAlerts.thresholds[type]}</p>
        <p><strong>Time:</strong> ${new Date().toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}</p>
        `;
        
        const mailOptions = {
            from: emailConfig.from,
            to: emailConfig.to,
            subject: subject,
            html: html
        };
        
        const info = await transporter.sendMail(mailOptions);
        console.log(`📧 Price alert sent: ${type.toUpperCase()} - $${price.toFixed(2)}`);
    } catch (error) {
        console.error('❌ Failed to send price alert:', error.message);
    }
}

async function startRealtimeQuotes() {
    try {
        console.log('🚀 Starting Coffee Robusta RC1 Realtime Quotes...');
        console.log('═══════════════════════════════════════════════════════');
          // Tạo session
        const chart = new client.Session.Chart();
          // Symbol hoạt động tốt cho Robusta Coffee       
           const workingSymbols = [
            'ICEEUR:RC1!',    // Robusta Coffee Continuous Contract - ICE Europe
            'ICEEUR:RCH2025', // Robusta Coffee March 2025
            'ICEEUR:RCK2025', // Robusta Coffee May 2025
            'ICEEUR:RCN2025', // Robusta Coffee July 2025
            'ICEEUR:RCU2025', // Robusta Coffee September 2025
            'ICEEUR:RCX2025', // Robusta Coffee November 2025
            'ICEEUR:RCF2026', // Robusta Coffee January 2026
            'NYSE:JO',        // Coffee ETF (backup)
            'NASDAQ:SBUX',    // Starbucks (backup)
        ];
        
        let currentSymbolIndex = 0;
        let connectedSymbol = null;
        let isConnected = false;
        
        function tryNextSymbol() {
            if (currentSymbolIndex >= workingSymbols.length) {
                console.error('❌ Không thể kết nối với bất kỳ symbol nào');
                return;
            }
            
            const symbol = workingSymbols[currentSymbolIndex];
            console.log(`🔍 Đang thử symbol: ${symbol}`);
            
            chart.setMarket(symbol, {
                timeframe: '1',
                range: 100,
            });
            
            currentSymbolIndex++;
        }
        
        // Bắt đầu với symbol đầu tiên
        tryNextSymbol();
        
        // Lắng nghe dữ liệu realtime
        chart.onSymbolLoaded(() => {
            connectedSymbol = workingSymbols[currentSymbolIndex-1];
            isConnected = true;
            console.log(`✅ Symbol ${connectedSymbol} loaded successfully`);
            console.log('🎯 Bắt đầu nhận dữ liệu realtime...');
        });

        chart.onUpdate(() => {
            if (!isConnected) return;
            
            const data = chart.periods[0];
            if (data && connectedSymbol) {
                const timestamp = new Date().toLocaleString('vi-VN', {
                    timeZone: 'Asia/Ho_Chi_Minh'
                });
                
                // Tính toán thay đổi giá
                const prevClose = data.open;
                const change = data.close - prevClose;
                const changePercent = ((change / prevClose) * 100).toFixed(2);
                const changeSymbol = change >= 0 ? '📈' : '📉';
                
                console.log(`\n📊 [${timestamp}] Coffee Robusta - ${connectedSymbol}`);
                console.log(`💰 Current Price: $${data.close.toFixed(2)}`);
                console.log(`${changeSymbol} Change: $${change.toFixed(2)} (${changePercent}%)`);
                console.log(`📊 High: $${data.max.toFixed(2)} | Low: $${data.min.toFixed(2)}`);
                console.log(`🔄 Volume: ${data.volume || 'N/A'}`);
                console.log(`🕐 Open: $${data.open.toFixed(2)}`);
                console.log('═'.repeat(60));

                // Cập nhật dữ liệu báo cáo
                reportData.updates.push({
                    timestamp,
                    price: data.close,
                    change,
                    changePercent,
                    high: data.max,
                    low: data.min,
                    volume: data.volume || 'N/A',
                    open: data.open
                });
                reportData.currentPrice = data.close;
                reportData.highPrice = data.max;
                reportData.lowPrice = data.min;
                reportData.symbol = connectedSymbol;

                // Kiểm tra cảnh báo giá
                if (emailConfig.priceAlerts.enabled) {
                    if (data.close >= emailConfig.priceAlerts.thresholds.high) {
                        sendPriceAlert(data.close, 'high');
                    } else if (data.close <= emailConfig.priceAlerts.thresholds.low) {
                        sendPriceAlert(data.close, 'low');
                    }
                }
            }
        });

        chart.onError((error) => {
            if (isConnected) {
                console.error(`❌ Connection lost for ${connectedSymbol}:`, error);
                console.log('🔄 Đang thử kết nối lại...');
                isConnected = false;
                setTimeout(() => {
                    tryNextSymbol();
                }, 3000);
            } else {
                console.error(`❌ Chart Error for ${workingSymbols[currentSymbolIndex-1]}:`, error);
                console.log('🔄 Thử symbol tiếp theo...');
                setTimeout(() => {
                    tryNextSymbol();
                }, 2000);
            }
        });

        // Giữ chương trình chạy
        process.on('SIGINT', () => {
            console.log('\n🛑 Stopping realtime quotes...');
            chart.delete();
            client.end();
            process.exit(0);
        });

        console.log('📡 Waiting for realtime data... (Press Ctrl+C to stop)');
        
    } catch (error) {
        console.error('❌ Error:', error);
    }
}

// Hàm kiểm tra và gửi báo cáo hàng ngày
function checkAndSendDailyReport() {
    const now = new Date();
    const today = now.toDateString(); // Lấy ngày hiện tại dưới dạng string
    
    // Kiểm tra xem đã gửi báo cáo hôm nay chưa
    if (reportData.lastEmailSent !== today && reportData.currentPrice) {
        console.log('📧 Sending daily report...');
        sendEmailReport();
        reportData.lastEmailSent = today;
    }
}

// Hàm lên lịch gửi báo cáo hàng ngày vào giờ đã cấu hình
function scheduleDailyReport() {
    const now = new Date();
    const reportHour = emailConfig.dailyReportTime || 8; // Mặc định 8:00 AM
    const nextReportTime = new Date();
    nextReportTime.setHours(reportHour, 0, 0, 0);
    
    // Nếu đã qua giờ báo cáo hôm nay, lên lịch cho ngày mai
    if (now >= nextReportTime) {
        nextReportTime.setDate(nextReportTime.getDate() + 1);
    }
    
    const timeUntilNextReport = nextReportTime - now;
    
    setTimeout(() => {
        checkAndSendDailyReport();
        // Sau đó lặp lại mỗi 24 giờ
        setInterval(checkAndSendDailyReport, 24 * 60 * 60 * 1000);
    }, timeUntilNextReport);
    
    console.log(`📧 Daily report scheduled for ${reportHour}:00 AM (Next: ${nextReportTime.toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })})`);
}

// Khởi tạo kết nối
client.onConnected(() => {
    console.log('🔗 Connected to TradingView');
    startRealtimeQuotes();
    
    // Lên lịch gửi báo cáo hàng ngày vào 8:00 AM
    scheduleDailyReport();
});

client.onDisconnected(() => {
    console.log('🔌 Disconnected from TradingView');
});

client.onError((error) => {
    console.error('❌ Connection Error:', error);
});